### ISSUE TITLE
The order_id parameter is not an UUID

### ISSUE THREAD

**Issue by iurisilvio** [TracyWebTech/braspag#5]
Your docs (https://braspag.readthedocs.org/en/0.2/braspag.html#creditcard-example) say the `order_id` is an UUID.

I use strings of digits as `order_id`s, like "123" or "2430".

The braspag docs says it is a `string(20)`, so an UUID is even invalid. It probably works, but does not respect specs, which is dangerous to some future webservice changes.

**Comment by seocam** [comment]
Thanks for the report. When this API was implemented Braspag examples did use UUIDs and that's why it's done like that. Do you have the latest PDF version?

I don't have contract with Braspag any longer so I don't  have the latest API documentation. If you do, please send me the pull request and the docs that I'll be happy to accept it.

Cheers!

**Comment by iurisilvio** [comment]
I realized you used Braspag 1.9 only after I created this issue. Doesn't make sense to make this pull request. I have docs v2.5, but I found v2.7 here (http://www.bancarioslitoral.org.br/uploads/arquivos/520cf62d4771f.pdf). I tested v2.5 with suds, it works fine, so I don't need this project. Probably this is the reason nobody asked for updates.

It is really difficult to make something open when it has a closed source dependency changing all the time. :/

Thanks!
